stages:
  - test

phpstan:
  stage: test
  image: php:8-fpm
  before_script:
    - composer i
    - composer require --dev phpstan/phpstan:1.4.8
  script:
    - php vendor/phpstan/phpstan/phpstan analyse --memory-limit 1024M -c phpstan.neon.dist --no-progress --error-format=junit > phpstan-report.xml
  after_script:
    - php vendor/phpstan/phpstan/phpstan analyse --memory-limit 1024M -c phpstan.neon.dist --no-progress
  artifacts:
    when: always
    reports:
      junit: phpstan-report.xml
    expire_in: 30 days
    paths:
      - phpstan-report.xml
  tags: ["kube-docker"]