stages:
  - test

phpstan:
  stage: test
  image: localhost:5000/php8
  before_script:
    - curl -s https://getcomposer.org/installer | php -- --filename=composer.phar
    - php composer.phar i
    - php composer.phar dump
  script:
    - php vendor/phpstan/phpstan/phpstan analyse --memory-limit 1024M -c phpstan.neon.dist --no-progress --error-format=junit > phpstan-report.xml
  after_script:
    - php vendor/phpstan/phpstan/phpstan analyse --memory-limit 1024M -c phpstan.neon.dist --no-progress
  artifacts:
    when: always
    reports:
      junit: phpstan-report.xml
    expire_in: 30 days
    paths:
      - phpstan-report.xml
  tags: ["kube-docker"]